### ISSUE TITLE
When Obsidian has been reopened. Error occurs

### ISSUE THREAD

**Issue by JerryI** [nhannht/obsidian-wolframjs#1]
<img width="1386" alt="Image" src="https://github.com/user-attachments/assets/5448f4fc-db4e-462f-b184-38372dba8943" />

**Comment by nhannht** [comment]
Note: 
- Obsidian by default using lucide icon, and the api have convention to auto switch color 
- For custom icon like above, the solution is implement css like this:
```css
.svg-icon.wolframjs path {
	fill: black
}
body.theme-dark  .svg-icon.wolframjs path {
	fill: white
}
```

The class `wolframjs` is the identify that based on how we register the icon 

In the future should using the css variable instead of black and white.
