### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by JerryI** [nhannht/obsidian-wolframjs#2]
<img width="202" alt="Image" src="https://github.com/user-attachments/assets/6d7b85ea-57d4-4a54-ac2f-4ea465badcd6" />

**Comment by nhannht** [comment]
Note: 
- Obsidian by default using lucide icon, and the api have convention to auto switch color 
- For custom icon like above, the solution is implement css like this:
```css
.svg-icon.wolframjs path {
	fill: black
}
body.theme-dark  .svg-icon.wolframjs path {
	fill: white
}
```

The class `wolframjs` is the identify that based on how we register the icon 

In the future should using the css variable instead of black and white.
